import type { TableColumnsType, TableProps } from 'antd';

export interface DataType {
    key: React.Key;
    TransactionDate: string;
    FileDate: string;
    DisplayDate: string;
    FlightNumber: string,
    GoodsServicesType: string,
    SAC: string,
    InvoiceNumber: string,
    PNR: string,
    Dep: string,
    Arr: string,
    PlaceOfEmbarkation: string,
    StateCode: string,
    CustomerGSTIN_UINNumber: string,
    CustomerName: string,
    EmailAddress: string,
    CustomerGSTRegistrationState: string,
    PassengerName: string,
    GSTIN: string,
    RegisteredAddress: string,
    nonTaxableFareComponent: string,
    taxableComponent: string,
    CGSTAmount: string,
    IGSTAmount: string,
    SGSTAmount: string,
    UGSTAmount: string,
    CGSTRate: string,
    IGSTRate: string,
    SGSTUGSTRate: string,
    IsProcessed: string,
    InvOrder: string,
    IsCredit: string,
    ServiceNo: string,
    Reason: string,
    ChangedBy: string,
    ChangedDate: string
  }

export const columns: TableColumnsType<DataType> = [
    {
      title: 'TransactionDate',
      dataIndex: 'TransactionDate',
    },
    {
      title: 'FileDate',
      dataIndex: 'FileDate',
    },
    {
      title: 'DisplayDate',
      dataIndex: 'DisplayDate',
    },
    {
      title: 'FlightNumber',
      dataIndex: 'FlightNumber',
    },
    {
      title: 'GoodsServicesType',
      dataIndex: 'GoodsServicesType',
    },
    {
      title: 'SAC',
      dataIndex: 'SAC',
    },
    {
      title: 'InvoiceNumber',
      dataIndex: 'InvoiceNumber',
    },
    {
      title: 'PNR',
      dataIndex: 'PNR',
    },
    {
      title: 'Dep',
      dataIndex: 'Dep',
    },
    {
      title: 'Arr',
      dataIndex: 'Arr',
    },
    {
      title: 'PlaceOfEmbarkation',
      dataIndex: 'PlaceOfEmbarkation',
    },
    {
      title: 'StateCode',
      dataIndex: 'StateCode',
    },
    {
      title: 'CustomerGSTIN_UINNumber',
      dataIndex: 'CustomerGSTIN_UINNumber',
    },
    {
      title: 'CustomerName',
      dataIndex: 'CustomerName',
    },
    {
      title: 'EmailAddress',
      dataIndex: 'EmailAddress',
    },
    {
      title: 'CustomerGSTRegistrationState',
      dataIndex: 'CustomerGSTRegistrationState',
    },
    {
      title: 'PassengerName',
      dataIndex: 'PassengerName',
    },
    {
      title: 'GSTIN',
      dataIndex: 'GSTIN',
    },
    {
      title: 'RegisteredAddress',
      dataIndex: 'RegisteredAddress',
    },
    {
      title: 'NonTaxableFareComponent',
      dataIndex: 'nonTaxableFareComponent',
    },
    {
      title: 'TaxableComponent',
      dataIndex: 'taxableComponent',
    },
    {
      title: 'CGSTAmount',
      dataIndex: 'CGSTAmount',
    },
    {
      title: 'IGSTAmount',
      dataIndex: 'IGSTAmount',
    },
    {
      title: 'SGSTAmount',
      dataIndex: 'SGSTAmount',
    },
    {
      title: 'UGSTAmount',
      dataIndex: 'UGSTAmount',
    },
    {
      title: 'CGSTRate',
      dataIndex: 'CGSTRate',
    },
    {
      title: 'IGSTRate',
      dataIndex: 'IGSTRate',
    },
    {
      title: 'SGSTUGSTRate',
      dataIndex: 'SGSTUGSTRate',
    },
    {
      title: 'IsProcessed',
      dataIndex: 'IsProcessed',
    },
    {
      title: 'InvOrder',
      dataIndex: 'InvOrder',
    },
    {
      title: 'IsCredit',
      dataIndex: 'IsCredit',
    },
    {
      title: 'ServiceNo',
      dataIndex: 'ServiceNo',
    },
    {
      title: 'Reason',
      dataIndex: 'Reason',
    },
    {
      title: 'ChangedBy',
      dataIndex: 'ChangedBy',
    },
    {
      title: 'ChangedDate',
      dataIndex: 'ChangedDate',
    },
  ];

export const data = [
    {
        TransactionDate	: '2024-06-19',
        FileDate: '2024-06-19	',
        DisplayDate:'2024-06-19	',
        FlightNumber: '2096',
        GoodsServicesType: 'Air Travel and related charges',
        SAC:'996425',
        InvoiceNumber: 'AS1242506AA02747',
        PNR: 'ES6ZMM',
        Dep:'GAU',
        Arr:'IXC',
        PlaceOfEmbarkation: 'Assam',
        StateCode: 'AS',
        CustomerGSTIN_UINNumber: '',
        CustomerName:'',
        EmailAddress:'abcd@gmail.com',
        CustomerGSTRegistrationState: '',
        PassengerName: 'Lalit Test',
        GSTIN: '18AABCI2726B1Z1',
        RegisteredAddress: 'LGBI Airport, Borjhar, Guwahati, Assam - 781015	',
        nonTaxableFareComponent: '0',
        taxableComponent: '16512',
        CGSTAmount: '0',
        IGSTAmount: '0',
        SGSTAmount: '0',
        UGSTAmount: '0',
        CGSTRate: '0',
        IGSTRate: '0',
        SGSTUGSTRate: '',
        IsProcessed: 'NULL',
        InvOrder:'1',
        IsCredit: '1',
        ServiceNo: '1',
        Reason: 'Generate invoice for Remaining PNR',
        ChangedBy: 'System',
        ChangedDate: '7/10/2024 5:33:11 PM'
    },
    {
        TransactionDate	: '2024-06-19',
        FileDate: '2024-06-19	',
        DisplayDate:'2024-06-19	',
        FlightNumber: '2096',
        GoodsServicesType: 'Air Travel and related charges',
        SAC:'996425',
        InvoiceNumber: 'AS1242506AA02747',
        PNR: 'ES6ZMM',
        Dep:'GAU',
        Arr:'IXC',
        PlaceOfEmbarkation: 'Assam',
        StateCode: 'AS',
        CustomerGSTIN_UINNumber: '',
        CustomerName:'',
        EmailAddress:'abcd@gmail.com',
        CustomerGSTRegistrationState: '',
        PassengerName: 'Lalit Test',
        GSTIN: '18AABCI2726B1Z1',
        RegisteredAddress: 'LGBI Airport, Borjhar, Guwahati, Assam - 781015	',
        nonTaxableFareComponent: '0',
        taxableComponent: '16512',
        CGSTAmount: '0',
        IGSTAmount: '0',
        SGSTAmount: '0',
        UGSTAmount: '0',
        CGSTRate: '0',
        IGSTRate: '0',
        SGSTUGSTRate: '',
        IsProcessed: 'NULL',
        InvOrder:'1',
        IsCredit: '1',
        ServiceNo: '1',
        Reason: 'Generate invoice for Remaining PNR',
        ChangedBy: 'System',
        ChangedDate: '7/10/2024 5:33:11 PM'
    },
    {
        TransactionDate	: '2024-06-19',
        FileDate: '2024-06-19	',
        DisplayDate:'2024-06-19	',
        FlightNumber: '2096',
        GoodsServicesType: 'Air Travel and related charges',
        SAC:'996425',
        InvoiceNumber: 'AS1242506AA02747',
        PNR: 'ES6ZMM',
        Dep:'GAU',
        Arr:'IXC',
        PlaceOfEmbarkation: 'Assam',
        StateCode: 'AS',
        CustomerGSTIN_UINNumber: '',
        CustomerName:'',
        EmailAddress:'abcd@gmail.com',
        CustomerGSTRegistrationState: '',
        PassengerName: 'Lalit Test',
        GSTIN: '18AABCI2726B1Z1',
        RegisteredAddress: 'LGBI Airport, Borjhar, Guwahati, Assam - 781015	',
        nonTaxableFareComponent: '0',
        taxableComponent: '16512',
        CGSTAmount: '0',
        IGSTAmount: '0',
        SGSTAmount: '0',
        UGSTAmount: '0',
        CGSTRate: '0',
        IGSTRate: '0',
        SGSTUGSTRate: '',
        IsProcessed: 'NULL',
        InvOrder:'1',
        IsCredit: '1',
        ServiceNo: '1',
        Reason: 'Generate invoice for Remaining PNR',
        ChangedBy: 'System',
        ChangedDate: '7/10/2024 5:33:11 PM'
    },
    {
        TransactionDate	: '2024-06-19',
        FileDate: '2024-06-19	',
        DisplayDate:'2024-06-19	',
        FlightNumber: '2096',
        GoodsServicesType: 'Air Travel and related charges',
        SAC:'996425',
        InvoiceNumber: 'AS1242506AA02747',
        PNR: 'ES6ZMM',
        Dep:'GAU',
        Arr:'IXC',
        PlaceOfEmbarkation: 'Assam',
        StateCode: 'AS',
        CustomerGSTIN_UINNumber: '',
        CustomerName:'',
        EmailAddress:'abcd@gmail.com',
        CustomerGSTRegistrationState: '',
        PassengerName: 'Lalit Test',
        GSTIN: '18AABCI2726B1Z1',
        RegisteredAddress: 'LGBI Airport, Borjhar, Guwahati, Assam - 781015	',
        nonTaxableFareComponent: '0',
        taxableComponent: '16512',
        CGSTAmount: '0',
        IGSTAmount: '0',
        SGSTAmount: '0',
        UGSTAmount: '0',
        CGSTRate: '0',
        IGSTRate: '0',
        SGSTUGSTRate: '',
        IsProcessed: 'NULL',
        InvOrder:'1',
        IsCredit: '1',
        ServiceNo: '1',
        Reason: 'Generate invoice for Remaining PNR',
        ChangedBy: 'System',
        ChangedDate: '7/10/2024 5:33:11 PM'
    },
    {
        TransactionDate	: '2024-06-19',
        FileDate: '2024-06-19	',
        DisplayDate:'2024-06-19	',
        FlightNumber: '2096',
        GoodsServicesType: 'Air Travel and related charges',
        SAC:'996425',
        InvoiceNumber: 'AS1242506AA02747',
        PNR: 'ES6ZMM',
        Dep:'GAU',
        Arr:'IXC',
        PlaceOfEmbarkation: 'Assam',
        StateCode: 'AS',
        CustomerGSTIN_UINNumber: '',
        CustomerName:'',
        EmailAddress:'abcd@gmail.com',
        CustomerGSTRegistrationState: '',
        PassengerName: 'Lalit Test',
        GSTIN: '18AABCI2726B1Z1',
        RegisteredAddress: 'LGBI Airport, Borjhar, Guwahati, Assam - 781015	',
        nonTaxableFareComponent: '0',
        taxableComponent: '16512',
        CGSTAmount: '0',
        IGSTAmount: '0',
        SGSTAmount: '0',
        UGSTAmount: '0',
        CGSTRate: '0',
        IGSTRate: '0',
        SGSTUGSTRate: '',
        IsProcessed: 'NULL',
        InvOrder:'1',
        IsCredit: '1',
        ServiceNo: '1',
        Reason: 'Generate invoice for Remaining PNR',
        ChangedBy: 'System',
        ChangedDate: '7/10/2024 5:33:11 PM'
    }
]